// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/document.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CameraState dco_decode_box_autoadd_camera_state(dynamic raw);

  @protected
  EntityCountSummary dco_decode_box_autoadd_entity_count_summary(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  HitResult dco_decode_box_autoadd_hit_result(dynamic raw);

  @protected
  OpenDocumentResponse dco_decode_box_autoadd_open_document_response(
    dynamic raw,
  );

  @protected
  RayHitResult dco_decode_box_autoadd_ray_hit_result(dynamic raw);

  @protected
  SnapResult dco_decode_box_autoadd_snap_result(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CameraState dco_decode_camera_state(dynamic raw);

  @protected
  DocumentEventInfo dco_decode_document_event_info(dynamic raw);

  @protected
  EntityCountSummary dco_decode_entity_count_summary(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FormatInfo dco_decode_format_info(dynamic raw);

  @protected
  HitResult dco_decode_hit_result(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DocumentEventInfo> dco_decode_list_document_event_info(dynamic raw);

  @protected
  List<FormatInfo> dco_decode_list_format_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<VisibilityChange> dco_decode_list_visibility_change(dynamic raw);

  @protected
  OpenDocumentResponse dco_decode_open_document_response(dynamic raw);

  @protected
  OpenTicket dco_decode_open_ticket(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  EntityCountSummary? dco_decode_opt_box_autoadd_entity_count_summary(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  HitResult? dco_decode_opt_box_autoadd_hit_result(dynamic raw);

  @protected
  OpenDocumentResponse? dco_decode_opt_box_autoadd_open_document_response(
    dynamic raw,
  );

  @protected
  RayHitResult? dco_decode_opt_box_autoadd_ray_hit_result(dynamic raw);

  @protected
  SnapResult? dco_decode_opt_box_autoadd_snap_result(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  RayHitResult dco_decode_ray_hit_result(dynamic raw);

  @protected
  SnapResult dco_decode_snap_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  ViewportInfo dco_decode_viewport_info(dynamic raw);

  @protected
  VisibilityChange dco_decode_visibility_change(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CameraState sse_decode_box_autoadd_camera_state(SseDeserializer deserializer);

  @protected
  EntityCountSummary sse_decode_box_autoadd_entity_count_summary(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HitResult sse_decode_box_autoadd_hit_result(SseDeserializer deserializer);

  @protected
  OpenDocumentResponse sse_decode_box_autoadd_open_document_response(
    SseDeserializer deserializer,
  );

  @protected
  RayHitResult sse_decode_box_autoadd_ray_hit_result(
    SseDeserializer deserializer,
  );

  @protected
  SnapResult sse_decode_box_autoadd_snap_result(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CameraState sse_decode_camera_state(SseDeserializer deserializer);

  @protected
  DocumentEventInfo sse_decode_document_event_info(
    SseDeserializer deserializer,
  );

  @protected
  EntityCountSummary sse_decode_entity_count_summary(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FormatInfo sse_decode_format_info(SseDeserializer deserializer);

  @protected
  HitResult sse_decode_hit_result(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DocumentEventInfo> sse_decode_list_document_event_info(
    SseDeserializer deserializer,
  );

  @protected
  List<FormatInfo> sse_decode_list_format_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<VisibilityChange> sse_decode_list_visibility_change(
    SseDeserializer deserializer,
  );

  @protected
  OpenDocumentResponse sse_decode_open_document_response(
    SseDeserializer deserializer,
  );

  @protected
  OpenTicket sse_decode_open_ticket(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  EntityCountSummary? sse_decode_opt_box_autoadd_entity_count_summary(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HitResult? sse_decode_opt_box_autoadd_hit_result(
    SseDeserializer deserializer,
  );

  @protected
  OpenDocumentResponse? sse_decode_opt_box_autoadd_open_document_response(
    SseDeserializer deserializer,
  );

  @protected
  RayHitResult? sse_decode_opt_box_autoadd_ray_hit_result(
    SseDeserializer deserializer,
  );

  @protected
  SnapResult? sse_decode_opt_box_autoadd_snap_result(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  RayHitResult sse_decode_ray_hit_result(SseDeserializer deserializer);

  @protected
  SnapResult sse_decode_snap_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ViewportInfo sse_decode_viewport_info(SseDeserializer deserializer);

  @protected
  VisibilityChange sse_decode_visibility_change(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_camera_state(
    CameraState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entity_count_summary(
    EntityCountSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_hit_result(
    HitResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_open_document_response(
    OpenDocumentResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ray_hit_result(
    RayHitResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_snap_result(
    SnapResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_camera_state(CameraState self, SseSerializer serializer);

  @protected
  void sse_encode_document_event_info(
    DocumentEventInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entity_count_summary(
    EntityCountSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_format_info(FormatInfo self, SseSerializer serializer);

  @protected
  void sse_encode_hit_result(HitResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_document_event_info(
    List<DocumentEventInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_format_info(
    List<FormatInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_visibility_change(
    List<VisibilityChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_document_response(
    OpenDocumentResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_ticket(OpenTicket self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_entity_count_summary(
    EntityCountSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_hit_result(
    HitResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_open_document_response(
    OpenDocumentResponse? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ray_hit_result(
    RayHitResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_snap_result(
    SnapResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_ray_hit_result(RayHitResult self, SseSerializer serializer);

  @protected
  void sse_encode_snap_result(SnapResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_viewport_info(ViewportInfo self, SseSerializer serializer);

  @protected
  void sse_encode_visibility_change(
    VisibilityChange self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
