// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/document.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1985162432;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cad_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiDocumentAddTextAnnotation({
    required BigInt sessionId,
    required String value,
    required double x,
    required double y,
    BigInt? entityId,
  });

  String crateApiDocumentAddTextAnnotation3D({
    required BigInt sessionId,
    required String value,
    required double x,
    required double y,
    required double z,
    BigInt? meshId,
  });

  String crateApiDocumentAnnotationCommand({
    required BigInt sessionId,
    required String annotationJson,
  });

  OpenTicket crateApiDocumentBeginOpenDocument({required String path});

  Future<CameraState> crateApiDocumentCameraStateDefault();

  bool crateApiDocumentCancelOpenDocument({required BigInt ticketId});

  bool crateApiDocumentCloseDocument({required BigInt sessionId});

  bool crateApiDocumentCloseViewport({required BigInt viewportId});

  void crateApiDocumentConfigureCache({required String directory});

  ViewportInfo crateApiDocumentCreateViewport({
    required BigInt sessionId,
    required int width,
    required int height,
    required double pixelRatio,
  });

  String crateApiDocumentDeleteAnnotation({
    required BigInt sessionId,
    required String annotationId,
  });

  Future<String> crateApiDocumentDocumentSummary({required BigInt sessionId});

  String crateApiDocumentExportAnnotations({required BigInt sessionId});

  Future<OpenDocumentResponse?> crateApiDocumentFinishOpenDocument({
    required BigInt ticketId,
  });

  HitResult? crateApiDocumentHitTest({
    required BigInt sessionId,
    required double x,
    required double y,
    required double tolerance,
  });

  Future<void> crateApiSimpleInitApp();

  String crateApiDocumentLoadAnnotations({
    required BigInt sessionId,
    required String databasePath,
  });

  double crateApiDocumentMeasureDistance2D({
    required double x1,
    required double y1,
    required double x2,
    required double y2,
  });

  double crateApiDocumentMeasureDistance3D({
    required double x1,
    required double y1,
    required double z1,
    required double x2,
    required double y2,
    required double z2,
  });

  Future<OpenDocumentResponse> crateApiDocumentOpenDocument({
    required String path,
  });

  List<DocumentEventInfo> crateApiDocumentPollDocumentEvents({
    required BigInt ticketId,
  });

  String crateApiDocumentRedo({required BigInt sessionId});

  void crateApiDocumentSaveAnnotations({
    required BigInt sessionId,
    required String databasePath,
  });

  void crateApiDocumentSetApplicationBackgrounded({required bool backgrounded});

  String crateApiDocumentSetVisibility({
    required BigInt sessionId,
    required BigInt itemId,
    required bool visible,
  });

  SnapResult? crateApiDocumentSnap({
    required BigInt sessionId,
    required double x,
    required double y,
    required double tolerance,
  });

  List<FormatInfo> crateApiDocumentSupportedFormats();

  String crateApiDocumentUndo({required BigInt sessionId});

  void crateApiDocumentUpdateCamera({
    required BigInt sessionId,
    required CameraState camera,
  });

  Future<String> crateApiDocumentViewportDocument({
    required BigInt sessionId,
    required double minX,
    required double minY,
    required double maxX,
    required double maxY,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiDocumentAddTextAnnotation({
    required BigInt sessionId,
    required String value,
    required double x,
    required double y,
    BigInt? entityId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(value, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_opt_box_autoadd_u_64(entityId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentAddTextAnnotationConstMeta,
        argValues: [sessionId, value, x, y, entityId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentAddTextAnnotationConstMeta =>
      const TaskConstMeta(
        debugName: "add_text_annotation",
        argNames: ["sessionId", "value", "x", "y", "entityId"],
      );

  @override
  String crateApiDocumentAddTextAnnotation3D({
    required BigInt sessionId,
    required String value,
    required double x,
    required double y,
    required double z,
    BigInt? meshId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(value, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_f_64(z, serializer);
          sse_encode_opt_box_autoadd_u_64(meshId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentAddTextAnnotation3DConstMeta,
        argValues: [sessionId, value, x, y, z, meshId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentAddTextAnnotation3DConstMeta =>
      const TaskConstMeta(
        debugName: "add_text_annotation_3d",
        argNames: ["sessionId", "value", "x", "y", "z", "meshId"],
      );

  @override
  String crateApiDocumentAnnotationCommand({
    required BigInt sessionId,
    required String annotationJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(annotationJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentAnnotationCommandConstMeta,
        argValues: [sessionId, annotationJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentAnnotationCommandConstMeta =>
      const TaskConstMeta(
        debugName: "annotation_command",
        argNames: ["sessionId", "annotationJson"],
      );

  @override
  OpenTicket crateApiDocumentBeginOpenDocument({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_open_ticket,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentBeginOpenDocumentConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentBeginOpenDocumentConstMeta =>
      const TaskConstMeta(debugName: "begin_open_document", argNames: ["path"]);

  @override
  Future<CameraState> crateApiDocumentCameraStateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_camera_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDocumentCameraStateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentCameraStateDefaultConstMeta =>
      const TaskConstMeta(debugName: "camera_state_default", argNames: []);

  @override
  bool crateApiDocumentCancelOpenDocument({required BigInt ticketId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(ticketId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDocumentCancelOpenDocumentConstMeta,
        argValues: [ticketId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentCancelOpenDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_open_document",
        argNames: ["ticketId"],
      );

  @override
  bool crateApiDocumentCloseDocument({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDocumentCloseDocumentConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentCloseDocumentConstMeta =>
      const TaskConstMeta(debugName: "close_document", argNames: ["sessionId"]);

  @override
  bool crateApiDocumentCloseViewport({required BigInt viewportId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(viewportId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDocumentCloseViewportConstMeta,
        argValues: [viewportId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentCloseViewportConstMeta =>
      const TaskConstMeta(
        debugName: "close_viewport",
        argNames: ["viewportId"],
      );

  @override
  void crateApiDocumentConfigureCache({required String directory}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directory, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentConfigureCacheConstMeta,
        argValues: [directory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentConfigureCacheConstMeta =>
      const TaskConstMeta(
        debugName: "configure_cache",
        argNames: ["directory"],
      );

  @override
  ViewportInfo crateApiDocumentCreateViewport({
    required BigInt sessionId,
    required int width,
    required int height,
    required double pixelRatio,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_f_64(pixelRatio, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_viewport_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentCreateViewportConstMeta,
        argValues: [sessionId, width, height, pixelRatio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentCreateViewportConstMeta =>
      const TaskConstMeta(
        debugName: "create_viewport",
        argNames: ["sessionId", "width", "height", "pixelRatio"],
      );

  @override
  String crateApiDocumentDeleteAnnotation({
    required BigInt sessionId,
    required String annotationId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(annotationId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentDeleteAnnotationConstMeta,
        argValues: [sessionId, annotationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentDeleteAnnotationConstMeta =>
      const TaskConstMeta(
        debugName: "delete_annotation",
        argNames: ["sessionId", "annotationId"],
      );

  @override
  Future<String> crateApiDocumentDocumentSummary({required BigInt sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentDocumentSummaryConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentDocumentSummaryConstMeta =>
      const TaskConstMeta(
        debugName: "document_summary",
        argNames: ["sessionId"],
      );

  @override
  String crateApiDocumentExportAnnotations({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentExportAnnotationsConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentExportAnnotationsConstMeta =>
      const TaskConstMeta(
        debugName: "export_annotations",
        argNames: ["sessionId"],
      );

  @override
  Future<OpenDocumentResponse?> crateApiDocumentFinishOpenDocument({
    required BigInt ticketId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(ticketId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_open_document_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentFinishOpenDocumentConstMeta,
        argValues: [ticketId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentFinishOpenDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "finish_open_document",
        argNames: ["ticketId"],
      );

  @override
  HitResult? crateApiDocumentHitTest({
    required BigInt sessionId,
    required double x,
    required double y,
    required double tolerance,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_f_64(tolerance, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_hit_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentHitTestConstMeta,
        argValues: [sessionId, x, y, tolerance],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentHitTestConstMeta => const TaskConstMeta(
    debugName: "hit_test",
    argNames: ["sessionId", "x", "y", "tolerance"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  String crateApiDocumentLoadAnnotations({
    required BigInt sessionId,
    required String databasePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(databasePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentLoadAnnotationsConstMeta,
        argValues: [sessionId, databasePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentLoadAnnotationsConstMeta =>
      const TaskConstMeta(
        debugName: "load_annotations",
        argNames: ["sessionId", "databasePath"],
      );

  @override
  double crateApiDocumentMeasureDistance2D({
    required double x1,
    required double y1,
    required double x2,
    required double y2,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(x1, serializer);
          sse_encode_f_64(y1, serializer);
          sse_encode_f_64(x2, serializer);
          sse_encode_f_64(y2, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDocumentMeasureDistance2DConstMeta,
        argValues: [x1, y1, x2, y2],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentMeasureDistance2DConstMeta =>
      const TaskConstMeta(
        debugName: "measure_distance_2d",
        argNames: ["x1", "y1", "x2", "y2"],
      );

  @override
  double crateApiDocumentMeasureDistance3D({
    required double x1,
    required double y1,
    required double z1,
    required double x2,
    required double y2,
    required double z2,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(x1, serializer);
          sse_encode_f_64(y1, serializer);
          sse_encode_f_64(z1, serializer);
          sse_encode_f_64(x2, serializer);
          sse_encode_f_64(y2, serializer);
          sse_encode_f_64(z2, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDocumentMeasureDistance3DConstMeta,
        argValues: [x1, y1, z1, x2, y2, z2],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentMeasureDistance3DConstMeta =>
      const TaskConstMeta(
        debugName: "measure_distance_3d",
        argNames: ["x1", "y1", "z1", "x2", "y2", "z2"],
      );

  @override
  Future<OpenDocumentResponse> crateApiDocumentOpenDocument({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_open_document_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentOpenDocumentConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentOpenDocumentConstMeta =>
      const TaskConstMeta(debugName: "open_document", argNames: ["path"]);

  @override
  List<DocumentEventInfo> crateApiDocumentPollDocumentEvents({
    required BigInt ticketId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(ticketId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_document_event_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentPollDocumentEventsConstMeta,
        argValues: [ticketId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentPollDocumentEventsConstMeta =>
      const TaskConstMeta(
        debugName: "poll_document_events",
        argNames: ["ticketId"],
      );

  @override
  String crateApiDocumentRedo({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentRedoConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentRedoConstMeta =>
      const TaskConstMeta(debugName: "redo", argNames: ["sessionId"]);

  @override
  void crateApiDocumentSaveAnnotations({
    required BigInt sessionId,
    required String databasePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(databasePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentSaveAnnotationsConstMeta,
        argValues: [sessionId, databasePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentSaveAnnotationsConstMeta =>
      const TaskConstMeta(
        debugName: "save_annotations",
        argNames: ["sessionId", "databasePath"],
      );

  @override
  void crateApiDocumentSetApplicationBackgrounded({
    required bool backgrounded,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(backgrounded, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDocumentSetApplicationBackgroundedConstMeta,
        argValues: [backgrounded],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentSetApplicationBackgroundedConstMeta =>
      const TaskConstMeta(
        debugName: "set_application_backgrounded",
        argNames: ["backgrounded"],
      );

  @override
  String crateApiDocumentSetVisibility({
    required BigInt sessionId,
    required BigInt itemId,
    required bool visible,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(itemId, serializer);
          sse_encode_bool(visible, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentSetVisibilityConstMeta,
        argValues: [sessionId, itemId, visible],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentSetVisibilityConstMeta =>
      const TaskConstMeta(
        debugName: "set_visibility",
        argNames: ["sessionId", "itemId", "visible"],
      );

  @override
  SnapResult? crateApiDocumentSnap({
    required BigInt sessionId,
    required double x,
    required double y,
    required double tolerance,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_f_64(tolerance, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_snap_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentSnapConstMeta,
        argValues: [sessionId, x, y, tolerance],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentSnapConstMeta => const TaskConstMeta(
    debugName: "snap",
    argNames: ["sessionId", "x", "y", "tolerance"],
  );

  @override
  List<FormatInfo> crateApiDocumentSupportedFormats() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_format_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDocumentSupportedFormatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentSupportedFormatsConstMeta =>
      const TaskConstMeta(debugName: "supported_formats", argNames: []);

  @override
  String crateApiDocumentUndo({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentUndoConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentUndoConstMeta =>
      const TaskConstMeta(debugName: "undo", argNames: ["sessionId"]);

  @override
  void crateApiDocumentUpdateCamera({
    required BigInt sessionId,
    required CameraState camera,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_box_autoadd_camera_state(camera, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentUpdateCameraConstMeta,
        argValues: [sessionId, camera],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentUpdateCameraConstMeta =>
      const TaskConstMeta(
        debugName: "update_camera",
        argNames: ["sessionId", "camera"],
      );

  @override
  Future<String> crateApiDocumentViewportDocument({
    required BigInt sessionId,
    required double minX,
    required double minY,
    required double maxX,
    required double maxY,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_f_64(minX, serializer);
          sse_encode_f_64(minY, serializer);
          sse_encode_f_64(maxX, serializer);
          sse_encode_f_64(maxY, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDocumentViewportDocumentConstMeta,
        argValues: [sessionId, minX, minY, maxX, maxY],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDocumentViewportDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "viewport_document",
        argNames: ["sessionId", "minX", "minY", "maxX", "maxY"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CameraState dco_decode_box_autoadd_camera_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_camera_state(raw);
  }

  @protected
  HitResult dco_decode_box_autoadd_hit_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_hit_result(raw);
  }

  @protected
  OpenDocumentResponse dco_decode_box_autoadd_open_document_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_open_document_response(raw);
  }

  @protected
  SnapResult dco_decode_box_autoadd_snap_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_snap_result(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  CameraState dco_decode_camera_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CameraState(
      centerX: dco_decode_f_64(arr[0]),
      centerY: dco_decode_f_64(arr[1]),
      centerZ: dco_decode_f_64(arr[2]),
      scale: dco_decode_f_64(arr[3]),
      yaw: dco_decode_f_64(arr[4]),
      pitch: dco_decode_f_64(arr[5]),
      perspective: dco_decode_bool(arr[6]),
    );
  }

  @protected
  DocumentEventInfo dco_decode_document_event_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DocumentEventInfo(
      kind: dco_decode_String(arr[0]),
      stage: dco_decode_String(arr[1]),
      progress: dco_decode_f_64(arr[2]),
      message: dco_decode_opt_String(arr[3]),
      sessionId: dco_decode_opt_box_autoadd_u_64(arr[4]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FormatInfo dco_decode_format_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return FormatInfo(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      extensions: dco_decode_list_String(arr[2]),
      sceneKind: dco_decode_String(arr[3]),
      supportLevel: dco_decode_String(arr[4]),
      available: dco_decode_bool(arr[5]),
      canMeasure: dco_decode_bool(arr[6]),
      note: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  HitResult dco_decode_hit_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HitResult(
      entityId: dco_decode_u_64(arr[0]),
      layerId: dco_decode_u_64(arr[1]),
      distance: dco_decode_f_64(arr[2]),
      entityKind: dco_decode_String(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DocumentEventInfo> dco_decode_list_document_event_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_document_event_info).toList();
  }

  @protected
  List<FormatInfo> dco_decode_list_format_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_format_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  OpenDocumentResponse dco_decode_open_document_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return OpenDocumentResponse(
      sessionId: dco_decode_u_64(arr[0]),
      formatId: dco_decode_String(arr[1]),
      sceneKind: dco_decode_String(arr[2]),
      displayName: dco_decode_String(arr[3]),
      fingerprint: dco_decode_String(arr[4]),
      documentJson: dco_decode_String(arr[5]),
      totalEntityCount: dco_decode_u_64(arr[6]),
      isPartial: dco_decode_bool(arr[7]),
    );
  }

  @protected
  OpenTicket dco_decode_open_ticket(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return OpenTicket(ticketId: dco_decode_u_64(arr[0]));
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  HitResult? dco_decode_opt_box_autoadd_hit_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_hit_result(raw);
  }

  @protected
  OpenDocumentResponse? dco_decode_opt_box_autoadd_open_document_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_open_document_response(raw);
  }

  @protected
  SnapResult? dco_decode_opt_box_autoadd_snap_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_snap_result(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SnapResult dco_decode_snap_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SnapResult(
      entityId: dco_decode_u_64(arr[0]),
      x: dco_decode_f_64(arr[1]),
      y: dco_decode_f_64(arr[2]),
      snapKind: dco_decode_String(arr[3]),
      distance: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  ViewportInfo dco_decode_viewport_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ViewportInfo(
      viewportId: dco_decode_u_64(arr[0]),
      textureId: dco_decode_i_64(arr[1]),
      rendererBackend: dco_decode_String(arr[2]),
      width: dco_decode_u_32(arr[3]),
      height: dco_decode_u_32(arr[4]),
      pixelRatio: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CameraState sse_decode_box_autoadd_camera_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_camera_state(deserializer));
  }

  @protected
  HitResult sse_decode_box_autoadd_hit_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_hit_result(deserializer));
  }

  @protected
  OpenDocumentResponse sse_decode_box_autoadd_open_document_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_open_document_response(deserializer));
  }

  @protected
  SnapResult sse_decode_box_autoadd_snap_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_snap_result(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  CameraState sse_decode_camera_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_centerX = sse_decode_f_64(deserializer);
    var var_centerY = sse_decode_f_64(deserializer);
    var var_centerZ = sse_decode_f_64(deserializer);
    var var_scale = sse_decode_f_64(deserializer);
    var var_yaw = sse_decode_f_64(deserializer);
    var var_pitch = sse_decode_f_64(deserializer);
    var var_perspective = sse_decode_bool(deserializer);
    return CameraState(
      centerX: var_centerX,
      centerY: var_centerY,
      centerZ: var_centerZ,
      scale: var_scale,
      yaw: var_yaw,
      pitch: var_pitch,
      perspective: var_perspective,
    );
  }

  @protected
  DocumentEventInfo sse_decode_document_event_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_stage = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_sessionId = sse_decode_opt_box_autoadd_u_64(deserializer);
    return DocumentEventInfo(
      kind: var_kind,
      stage: var_stage,
      progress: var_progress,
      message: var_message,
      sessionId: var_sessionId,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FormatInfo sse_decode_format_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_extensions = sse_decode_list_String(deserializer);
    var var_sceneKind = sse_decode_String(deserializer);
    var var_supportLevel = sse_decode_String(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_canMeasure = sse_decode_bool(deserializer);
    var var_note = sse_decode_opt_String(deserializer);
    return FormatInfo(
      id: var_id,
      displayName: var_displayName,
      extensions: var_extensions,
      sceneKind: var_sceneKind,
      supportLevel: var_supportLevel,
      available: var_available,
      canMeasure: var_canMeasure,
      note: var_note,
    );
  }

  @protected
  HitResult sse_decode_hit_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entityId = sse_decode_u_64(deserializer);
    var var_layerId = sse_decode_u_64(deserializer);
    var var_distance = sse_decode_f_64(deserializer);
    var var_entityKind = sse_decode_String(deserializer);
    return HitResult(
      entityId: var_entityId,
      layerId: var_layerId,
      distance: var_distance,
      entityKind: var_entityKind,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DocumentEventInfo> sse_decode_list_document_event_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DocumentEventInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_document_event_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<FormatInfo> sse_decode_list_format_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FormatInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_format_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  OpenDocumentResponse sse_decode_open_document_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_64(deserializer);
    var var_formatId = sse_decode_String(deserializer);
    var var_sceneKind = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    var var_documentJson = sse_decode_String(deserializer);
    var var_totalEntityCount = sse_decode_u_64(deserializer);
    var var_isPartial = sse_decode_bool(deserializer);
    return OpenDocumentResponse(
      sessionId: var_sessionId,
      formatId: var_formatId,
      sceneKind: var_sceneKind,
      displayName: var_displayName,
      fingerprint: var_fingerprint,
      documentJson: var_documentJson,
      totalEntityCount: var_totalEntityCount,
      isPartial: var_isPartial,
    );
  }

  @protected
  OpenTicket sse_decode_open_ticket(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ticketId = sse_decode_u_64(deserializer);
    return OpenTicket(ticketId: var_ticketId);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  HitResult? sse_decode_opt_box_autoadd_hit_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_hit_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OpenDocumentResponse? sse_decode_opt_box_autoadd_open_document_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_open_document_response(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SnapResult? sse_decode_opt_box_autoadd_snap_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_snap_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SnapResult sse_decode_snap_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entityId = sse_decode_u_64(deserializer);
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_snapKind = sse_decode_String(deserializer);
    var var_distance = sse_decode_f_64(deserializer);
    return SnapResult(
      entityId: var_entityId,
      x: var_x,
      y: var_y,
      snapKind: var_snapKind,
      distance: var_distance,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  ViewportInfo sse_decode_viewport_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_viewportId = sse_decode_u_64(deserializer);
    var var_textureId = sse_decode_i_64(deserializer);
    var var_rendererBackend = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_pixelRatio = sse_decode_f_64(deserializer);
    return ViewportInfo(
      viewportId: var_viewportId,
      textureId: var_textureId,
      rendererBackend: var_rendererBackend,
      width: var_width,
      height: var_height,
      pixelRatio: var_pixelRatio,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_camera_state(
    CameraState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_camera_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_hit_result(
    HitResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_hit_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_open_document_response(
    OpenDocumentResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_open_document_response(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_snap_result(
    SnapResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_snap_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_camera_state(CameraState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.centerX, serializer);
    sse_encode_f_64(self.centerY, serializer);
    sse_encode_f_64(self.centerZ, serializer);
    sse_encode_f_64(self.scale, serializer);
    sse_encode_f_64(self.yaw, serializer);
    sse_encode_f_64(self.pitch, serializer);
    sse_encode_bool(self.perspective, serializer);
  }

  @protected
  void sse_encode_document_event_info(
    DocumentEventInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.stage, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sessionId, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_format_info(FormatInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_list_String(self.extensions, serializer);
    sse_encode_String(self.sceneKind, serializer);
    sse_encode_String(self.supportLevel, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_bool(self.canMeasure, serializer);
    sse_encode_opt_String(self.note, serializer);
  }

  @protected
  void sse_encode_hit_result(HitResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.entityId, serializer);
    sse_encode_u_64(self.layerId, serializer);
    sse_encode_f_64(self.distance, serializer);
    sse_encode_String(self.entityKind, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_document_event_info(
    List<DocumentEventInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_document_event_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_format_info(
    List<FormatInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_format_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_open_document_response(
    OpenDocumentResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sessionId, serializer);
    sse_encode_String(self.formatId, serializer);
    sse_encode_String(self.sceneKind, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.fingerprint, serializer);
    sse_encode_String(self.documentJson, serializer);
    sse_encode_u_64(self.totalEntityCount, serializer);
    sse_encode_bool(self.isPartial, serializer);
  }

  @protected
  void sse_encode_open_ticket(OpenTicket self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.ticketId, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_hit_result(
    HitResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_hit_result(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_open_document_response(
    OpenDocumentResponse? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_open_document_response(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_snap_result(
    SnapResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_snap_result(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_snap_result(SnapResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.entityId, serializer);
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_String(self.snapKind, serializer);
    sse_encode_f_64(self.distance, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_viewport_info(ViewportInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.viewportId, serializer);
    sse_encode_i_64(self.textureId, serializer);
    sse_encode_String(self.rendererBackend, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_f_64(self.pixelRatio, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
