// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `angle_on_arc`, `append_nearby_curves`, `apply_annotation`, `begin_open_document_impl`, `build_entity_statistics`, `circle_intersections`, `contains`, `cross`, `curve_intersections`, `distance_to`, `empty_bounds`, `entity_area`, `entity_distance`, `entity_id`, `entity_kind`, `entity_length`, `format_id`, `has_node`, `invalidate_session_viewports`, `load_cached_document`, `move_history`, `nearest_intersection`, `normalized_arc_sweep`, `open_document_internal`, `point_on_circle`, `point_segment_distance`, `push_ticket_event`, `scene_cache_path`, `scene_kind`, `scene_packet_internal`, `segment_circle_intersections`, `segment_intersection`, `serialize_session_document`, `serialize_session_view`, `set_node_visibility`, `snap_points`, `source_state`, `spatial_candidates`, `worker_threads`, `write_cached_document`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedSceneRef`, `CachedScene`, `DocumentSession`, `MeasuredTextBounds`, `NativeViewportState`, `OpenTicketState`, `SceneCacheHeaderRef`, `SceneCacheHeader`, `SnapCurve`, `TextLayoutItem`, `TicketSceneSink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `partial`, `progress`

List<FormatInfo> supportedFormats() =>
    RustLib.instance.api.crateApiDocumentSupportedFormats();

void configureCache({required String directory}) =>
    RustLib.instance.api.crateApiDocumentConfigureCache(directory: directory);

/// Compatibility wrapper retained for one API version. New UI code should use
/// begin_open_document/poll_document_events/finish_open_document so opening is
/// cancellable and progress never blocks the Dart isolate.
Future<OpenDocumentResponse> openDocument({required String path}) =>
    RustLib.instance.api.crateApiDocumentOpenDocument(path: path);

OpenTicket beginOpenDocument({required String path}) =>
    RustLib.instance.api.crateApiDocumentBeginOpenDocument(path: path);

/// Metadata-first open; the UI fetches lossless packed geometry (2D after
/// text-envelope refinement). The legacy JSON open APIs remain compatible.
OpenTicket beginOpenDocumentCompact({required String path}) =>
    RustLib.instance.api.crateApiDocumentBeginOpenDocumentCompact(path: path);

List<DocumentEventInfo> pollDocumentEvents({required BigInt ticketId}) =>
    RustLib.instance.api.crateApiDocumentPollDocumentEvents(ticketId: ticketId);

bool cancelOpenDocument({required BigInt ticketId}) =>
    RustLib.instance.api.crateApiDocumentCancelOpenDocument(ticketId: ticketId);

Future<OpenDocumentResponse?> finishOpenDocument({required BigInt ticketId}) =>
    RustLib.instance.api.crateApiDocumentFinishOpenDocument(ticketId: ticketId);

void setApplicationBackgrounded({required bool backgrounded}) => RustLib
    .instance
    .api
    .crateApiDocumentSetApplicationBackgrounded(backgrounded: backgrounded);

Future<String> documentSummary({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentDocumentSummary(sessionId: sessionId);

/// Bounded text-only pages, never a full drawing transfer. The cursor is a
/// scene-vector offset, not a text offset (no rescanning earlier geometry).
Future<String> textLayoutBatch({
  required BigInt sessionId,
  required BigInt start,
}) => RustLib.instance.api.crateApiDocumentTextLayoutBatch(
  sessionId: sessionId,
  start: start,
);

/// Validate the entire packet before mutating a session. Envelopes are runtime
/// data: never trust a cache produced with different device/source fonts.
Future<void> applyTextLayoutBounds({
  required BigInt sessionId,
  required String packet,
}) => RustLib.instance.api.crateApiDocumentApplyTextLayoutBounds(
  sessionId: sessionId,
  packet: packet,
);

/// Commit only after every label was measured. Rebuild once, not per packet.
Future<String> finalizeTextLayout({required BigInt sessionId}) => RustLib
    .instance
    .api
    .crateApiDocumentFinalizeTextLayout(sessionId: sessionId);

Future<String> viewportDocument({
  required BigInt sessionId,
  required double minX,
  required double minY,
  required double maxX,
  required double maxY,
}) => RustLib.instance.api.crateApiDocumentViewportDocument(
  sessionId: sessionId,
  minX: minX,
  minY: minY,
  maxX: maxX,
  maxY: maxY,
);

Future<Uint8List> documentPacket({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentDocumentPacket(sessionId: sessionId);

Future<Uint8List> viewportPacket({
  required BigInt sessionId,
  required double minX,
  required double minY,
  required double maxX,
  required double maxY,
}) => RustLib.instance.api.crateApiDocumentViewportPacket(
  sessionId: sessionId,
  minX: minX,
  minY: minY,
  maxX: maxX,
  maxY: maxY,
);

Future<bool> closeDocument({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentCloseDocument(sessionId: sessionId);

ViewportInfo createViewport({
  required BigInt sessionId,
  required int width,
  required int height,
  required double pixelRatio,
}) => RustLib.instance.api.crateApiDocumentCreateViewport(
  sessionId: sessionId,
  width: width,
  height: height,
  pixelRatio: pixelRatio,
);

bool closeViewport({required BigInt viewportId}) =>
    RustLib.instance.api.crateApiDocumentCloseViewport(viewportId: viewportId);

void updateCamera({required BigInt sessionId, required CameraState camera}) =>
    RustLib.instance.api.crateApiDocumentUpdateCamera(
      sessionId: sessionId,
      camera: camera,
    );

String setVisibility({
  required BigInt sessionId,
  required BigInt itemId,
  required bool visible,
}) => RustLib.instance.api.crateApiDocumentSetVisibility(
  sessionId: sessionId,
  itemId: itemId,
  visible: visible,
);

String setVisibilities({
  required BigInt sessionId,
  required List<VisibilityChange> changes,
}) => RustLib.instance.api.crateApiDocumentSetVisibilities(
  sessionId: sessionId,
  changes: changes,
);

/// Run candidate geometry checks on a bridge worker, never the UI thread.
Future<HitResult?> hitTest({
  required BigInt sessionId,
  required double x,
  required double y,
  required double tolerance,
}) => RustLib.instance.api.crateApiDocumentHitTest(
  sessionId: sessionId,
  x: x,
  y: y,
  tolerance: tolerance,
);

/// Worker-isolate ray pick against the retained, unsampled source triangles.
Future<RayHitResult?> hitTestRay({
  required BigInt sessionId,
  required double ox,
  required double oy,
  required double oz,
  required double dx,
  required double dy,
  required double dz,
}) => RustLib.instance.api.crateApiDocumentHitTestRay(
  sessionId: sessionId,
  ox: ox,
  oy: oy,
  oz: oz,
  dx: dx,
  dy: dy,
  dz: dz,
);

EntityCountSummary? entityCountSummary({
  required BigInt sessionId,
  required BigInt entityId,
}) => RustLib.instance.api.crateApiDocumentEntityCountSummary(
  sessionId: sessionId,
  entityId: entityId,
);

Future<SnapResult?> snap({
  required BigInt sessionId,
  required double x,
  required double y,
  required double tolerance,
}) => RustLib.instance.api.crateApiDocumentSnap(
  sessionId: sessionId,
  x: x,
  y: y,
  tolerance: tolerance,
);

/// Finds the nearest geometric intersection within the pick aperture.
///
/// This is separate from [`snap`] so tools that explicitly collect a boundary
/// can prefer a crossing without changing the nearest-snap behaviour used by
/// distance, coordinate and editing tools.
Future<SnapResult?> snapIntersection({
  required BigInt sessionId,
  required double x,
  required double y,
  required double tolerance,
}) => RustLib.instance.api.crateApiDocumentSnapIntersection(
  sessionId: sessionId,
  x: x,
  y: y,
  tolerance: tolerance,
);

double measureDistance2D({
  required double x1,
  required double y1,
  required double x2,
  required double y2,
}) => RustLib.instance.api.crateApiDocumentMeasureDistance2D(
  x1: x1,
  y1: y1,
  x2: x2,
  y2: y2,
);

double measureDistance3D({
  required double x1,
  required double y1,
  required double z1,
  required double x2,
  required double y2,
  required double z2,
}) => RustLib.instance.api.crateApiDocumentMeasureDistance3D(
  x1: x1,
  y1: y1,
  z1: z1,
  x2: x2,
  y2: y2,
  z2: z2,
);

String annotationCommand({
  required BigInt sessionId,
  required String annotationJson,
}) => RustLib.instance.api.crateApiDocumentAnnotationCommand(
  sessionId: sessionId,
  annotationJson: annotationJson,
);

String addTextAnnotation({
  required BigInt sessionId,
  required String value,
  required double x,
  required double y,
  BigInt? entityId,
}) => RustLib.instance.api.crateApiDocumentAddTextAnnotation(
  sessionId: sessionId,
  value: value,
  x: x,
  y: y,
  entityId: entityId,
);

String addTextAnnotation3D({
  required BigInt sessionId,
  required String value,
  required double x,
  required double y,
  required double z,
  BigInt? meshId,
}) => RustLib.instance.api.crateApiDocumentAddTextAnnotation3D(
  sessionId: sessionId,
  value: value,
  x: x,
  y: y,
  z: z,
  meshId: meshId,
);

String deleteAnnotation({
  required BigInt sessionId,
  required String annotationId,
}) => RustLib.instance.api.crateApiDocumentDeleteAnnotation(
  sessionId: sessionId,
  annotationId: annotationId,
);

String undo({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentUndo(sessionId: sessionId);

String redo({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentRedo(sessionId: sessionId);

String exportAnnotations({required BigInt sessionId}) => RustLib.instance.api
    .crateApiDocumentExportAnnotations(sessionId: sessionId);

void saveAnnotations({
  required BigInt sessionId,
  required String databasePath,
}) => RustLib.instance.api.crateApiDocumentSaveAnnotations(
  sessionId: sessionId,
  databasePath: databasePath,
);

String loadAnnotations({
  required BigInt sessionId,
  required String databasePath,
}) => RustLib.instance.api.crateApiDocumentLoadAnnotations(
  sessionId: sessionId,
  databasePath: databasePath,
);

class CameraState {
  final double centerX;
  final double centerY;
  final double centerZ;
  final double scale;
  final double yaw;
  final double pitch;
  final bool perspective;

  const CameraState({
    required this.centerX,
    required this.centerY,
    required this.centerZ,
    required this.scale,
    required this.yaw,
    required this.pitch,
    required this.perspective,
  });

  static Future<CameraState> default_() =>
      RustLib.instance.api.crateApiDocumentCameraStateDefault();

  @override
  int get hashCode =>
      centerX.hashCode ^
      centerY.hashCode ^
      centerZ.hashCode ^
      scale.hashCode ^
      yaw.hashCode ^
      pitch.hashCode ^
      perspective.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraState &&
          runtimeType == other.runtimeType &&
          centerX == other.centerX &&
          centerY == other.centerY &&
          centerZ == other.centerZ &&
          scale == other.scale &&
          yaw == other.yaw &&
          pitch == other.pitch &&
          perspective == other.perspective;
}

class DocumentEventInfo {
  final String kind;
  final String stage;
  final double progress;
  final String? message;
  final BigInt? sessionId;

  const DocumentEventInfo({
    required this.kind,
    required this.stage,
    required this.progress,
    this.message,
    this.sessionId,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      stage.hashCode ^
      progress.hashCode ^
      message.hashCode ^
      sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentEventInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          stage == other.stage &&
          progress == other.progress &&
          message == other.message &&
          sessionId == other.sessionId;
}

class EntityCountSummary {
  final String entityKind;
  final BigInt layerId;
  final BigInt sameKindInLayer;
  final BigInt sameKindInDocument;
  final double? sameKindLengthInLayer;
  final double? sameKindLengthInDocument;
  final double? sameKindAreaInLayer;
  final double? sameKindAreaInDocument;

  const EntityCountSummary({
    required this.entityKind,
    required this.layerId,
    required this.sameKindInLayer,
    required this.sameKindInDocument,
    this.sameKindLengthInLayer,
    this.sameKindLengthInDocument,
    this.sameKindAreaInLayer,
    this.sameKindAreaInDocument,
  });

  @override
  int get hashCode =>
      entityKind.hashCode ^
      layerId.hashCode ^
      sameKindInLayer.hashCode ^
      sameKindInDocument.hashCode ^
      sameKindLengthInLayer.hashCode ^
      sameKindLengthInDocument.hashCode ^
      sameKindAreaInLayer.hashCode ^
      sameKindAreaInDocument.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityCountSummary &&
          runtimeType == other.runtimeType &&
          entityKind == other.entityKind &&
          layerId == other.layerId &&
          sameKindInLayer == other.sameKindInLayer &&
          sameKindInDocument == other.sameKindInDocument &&
          sameKindLengthInLayer == other.sameKindLengthInLayer &&
          sameKindLengthInDocument == other.sameKindLengthInDocument &&
          sameKindAreaInLayer == other.sameKindAreaInLayer &&
          sameKindAreaInDocument == other.sameKindAreaInDocument;
}

class FormatInfo {
  final String id;
  final String displayName;
  final List<String> extensions;
  final String sceneKind;
  final String supportLevel;
  final bool available;
  final bool canMeasure;
  final String? note;

  const FormatInfo({
    required this.id,
    required this.displayName,
    required this.extensions,
    required this.sceneKind,
    required this.supportLevel,
    required this.available,
    required this.canMeasure,
    this.note,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      extensions.hashCode ^
      sceneKind.hashCode ^
      supportLevel.hashCode ^
      available.hashCode ^
      canMeasure.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          extensions == other.extensions &&
          sceneKind == other.sceneKind &&
          supportLevel == other.supportLevel &&
          available == other.available &&
          canMeasure == other.canMeasure &&
          note == other.note;
}

class HitResult {
  final BigInt entityId;
  final BigInt layerId;
  final double distance;
  final String entityKind;

  const HitResult({
    required this.entityId,
    required this.layerId,
    required this.distance,
    required this.entityKind,
  });

  @override
  int get hashCode =>
      entityId.hashCode ^
      layerId.hashCode ^
      distance.hashCode ^
      entityKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HitResult &&
          runtimeType == other.runtimeType &&
          entityId == other.entityId &&
          layerId == other.layerId &&
          distance == other.distance &&
          entityKind == other.entityKind;
}

class OpenDocumentResponse {
  final BigInt sessionId;
  final String formatId;
  final String sceneKind;
  final String displayName;
  final String fingerprint;
  final String documentJson;
  final BigInt totalEntityCount;
  final bool isPartial;

  const OpenDocumentResponse({
    required this.sessionId,
    required this.formatId,
    required this.sceneKind,
    required this.displayName,
    required this.fingerprint,
    required this.documentJson,
    required this.totalEntityCount,
    required this.isPartial,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      formatId.hashCode ^
      sceneKind.hashCode ^
      displayName.hashCode ^
      fingerprint.hashCode ^
      documentJson.hashCode ^
      totalEntityCount.hashCode ^
      isPartial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenDocumentResponse &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          formatId == other.formatId &&
          sceneKind == other.sceneKind &&
          displayName == other.displayName &&
          fingerprint == other.fingerprint &&
          documentJson == other.documentJson &&
          totalEntityCount == other.totalEntityCount &&
          isPartial == other.isPartial;
}

class OpenTicket {
  final BigInt ticketId;

  const OpenTicket({required this.ticketId});

  @override
  int get hashCode => ticketId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenTicket &&
          runtimeType == other.runtimeType &&
          ticketId == other.ticketId;
}

class RayHitResult {
  final BigInt meshId;
  final BigInt triangleIndex;
  final double x;
  final double y;
  final double z;
  final double distance;

  const RayHitResult({
    required this.meshId,
    required this.triangleIndex,
    required this.x,
    required this.y,
    required this.z,
    required this.distance,
  });

  @override
  int get hashCode =>
      meshId.hashCode ^
      triangleIndex.hashCode ^
      x.hashCode ^
      y.hashCode ^
      z.hashCode ^
      distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RayHitResult &&
          runtimeType == other.runtimeType &&
          meshId == other.meshId &&
          triangleIndex == other.triangleIndex &&
          x == other.x &&
          y == other.y &&
          z == other.z &&
          distance == other.distance;
}

class SnapResult {
  final BigInt entityId;
  final double x;
  final double y;
  final String snapKind;
  final double distance;

  const SnapResult({
    required this.entityId,
    required this.x,
    required this.y,
    required this.snapKind,
    required this.distance,
  });

  @override
  int get hashCode =>
      entityId.hashCode ^
      x.hashCode ^
      y.hashCode ^
      snapKind.hashCode ^
      distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapResult &&
          runtimeType == other.runtimeType &&
          entityId == other.entityId &&
          x == other.x &&
          y == other.y &&
          snapKind == other.snapKind &&
          distance == other.distance;
}

class ViewportInfo {
  final BigInt viewportId;
  final PlatformInt64 textureId;
  final String rendererBackend;
  final int width;
  final int height;
  final double pixelRatio;

  const ViewportInfo({
    required this.viewportId,
    required this.textureId,
    required this.rendererBackend,
    required this.width,
    required this.height,
    required this.pixelRatio,
  });

  @override
  int get hashCode =>
      viewportId.hashCode ^
      textureId.hashCode ^
      rendererBackend.hashCode ^
      width.hashCode ^
      height.hashCode ^
      pixelRatio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportInfo &&
          runtimeType == other.runtimeType &&
          viewportId == other.viewportId &&
          textureId == other.textureId &&
          rendererBackend == other.rendererBackend &&
          width == other.width &&
          height == other.height &&
          pixelRatio == other.pixelRatio;
}

class VisibilityChange {
  final BigInt itemId;
  final bool visible;

  const VisibilityChange({required this.itemId, required this.visible});

  @override
  int get hashCode => itemId.hashCode ^ visible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisibilityChange &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          visible == other.visible;
}
