// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_annotation`, `empty_bounds`, `entity_distance`, `entity_kind`, `format_id`, `invalidate_session_viewports`, `load_cached_document`, `move_history`, `open_document_internal`, `point_segment_distance`, `push_ticket_event`, `scene_cache_path`, `scene_kind`, `serialize_session_document`, `set_node_visibility`, `snap_points`, `source_state`, `spatial_candidates`, `write_cached_document`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DocumentSession`, `NativeViewportState`, `OpenTicketState`, `SceneCacheEnvelope`, `TicketSceneSink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `partial`, `progress`

List<FormatInfo> supportedFormats() =>
    RustLib.instance.api.crateApiDocumentSupportedFormats();

void configureCache({required String directory}) =>
    RustLib.instance.api.crateApiDocumentConfigureCache(directory: directory);

/// Compatibility wrapper retained for one API version. New UI code should use
/// begin_open_document/poll_document_events/finish_open_document so opening is
/// cancellable and progress never blocks the Dart isolate.
Future<OpenDocumentResponse> openDocument({required String path}) =>
    RustLib.instance.api.crateApiDocumentOpenDocument(path: path);

OpenTicket beginOpenDocument({required String path}) =>
    RustLib.instance.api.crateApiDocumentBeginOpenDocument(path: path);

List<DocumentEventInfo> pollDocumentEvents({required BigInt ticketId}) =>
    RustLib.instance.api.crateApiDocumentPollDocumentEvents(ticketId: ticketId);

bool cancelOpenDocument({required BigInt ticketId}) =>
    RustLib.instance.api.crateApiDocumentCancelOpenDocument(ticketId: ticketId);

Future<OpenDocumentResponse?> finishOpenDocument({required BigInt ticketId}) =>
    RustLib.instance.api.crateApiDocumentFinishOpenDocument(ticketId: ticketId);

void setApplicationBackgrounded({required bool backgrounded}) => RustLib
    .instance
    .api
    .crateApiDocumentSetApplicationBackgrounded(backgrounded: backgrounded);

Future<String> documentSummary({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentDocumentSummary(sessionId: sessionId);

Future<String> viewportDocument({
  required BigInt sessionId,
  required double minX,
  required double minY,
  required double maxX,
  required double maxY,
}) => RustLib.instance.api.crateApiDocumentViewportDocument(
  sessionId: sessionId,
  minX: minX,
  minY: minY,
  maxX: maxX,
  maxY: maxY,
);

bool closeDocument({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentCloseDocument(sessionId: sessionId);

ViewportInfo createViewport({
  required BigInt sessionId,
  required int width,
  required int height,
  required double pixelRatio,
}) => RustLib.instance.api.crateApiDocumentCreateViewport(
  sessionId: sessionId,
  width: width,
  height: height,
  pixelRatio: pixelRatio,
);

bool closeViewport({required BigInt viewportId}) =>
    RustLib.instance.api.crateApiDocumentCloseViewport(viewportId: viewportId);

void updateCamera({required BigInt sessionId, required CameraState camera}) =>
    RustLib.instance.api.crateApiDocumentUpdateCamera(
      sessionId: sessionId,
      camera: camera,
    );

String setVisibility({
  required BigInt sessionId,
  required BigInt itemId,
  required bool visible,
}) => RustLib.instance.api.crateApiDocumentSetVisibility(
  sessionId: sessionId,
  itemId: itemId,
  visible: visible,
);

HitResult? hitTest({
  required BigInt sessionId,
  required double x,
  required double y,
  required double tolerance,
}) => RustLib.instance.api.crateApiDocumentHitTest(
  sessionId: sessionId,
  x: x,
  y: y,
  tolerance: tolerance,
);

SnapResult? snap({
  required BigInt sessionId,
  required double x,
  required double y,
  required double tolerance,
}) => RustLib.instance.api.crateApiDocumentSnap(
  sessionId: sessionId,
  x: x,
  y: y,
  tolerance: tolerance,
);

double measureDistance2D({
  required double x1,
  required double y1,
  required double x2,
  required double y2,
}) => RustLib.instance.api.crateApiDocumentMeasureDistance2D(
  x1: x1,
  y1: y1,
  x2: x2,
  y2: y2,
);

double measureDistance3D({
  required double x1,
  required double y1,
  required double z1,
  required double x2,
  required double y2,
  required double z2,
}) => RustLib.instance.api.crateApiDocumentMeasureDistance3D(
  x1: x1,
  y1: y1,
  z1: z1,
  x2: x2,
  y2: y2,
  z2: z2,
);

String annotationCommand({
  required BigInt sessionId,
  required String annotationJson,
}) => RustLib.instance.api.crateApiDocumentAnnotationCommand(
  sessionId: sessionId,
  annotationJson: annotationJson,
);

String addTextAnnotation({
  required BigInt sessionId,
  required String value,
  required double x,
  required double y,
  BigInt? entityId,
}) => RustLib.instance.api.crateApiDocumentAddTextAnnotation(
  sessionId: sessionId,
  value: value,
  x: x,
  y: y,
  entityId: entityId,
);

String addTextAnnotation3D({
  required BigInt sessionId,
  required String value,
  required double x,
  required double y,
  required double z,
  BigInt? meshId,
}) => RustLib.instance.api.crateApiDocumentAddTextAnnotation3D(
  sessionId: sessionId,
  value: value,
  x: x,
  y: y,
  z: z,
  meshId: meshId,
);

String deleteAnnotation({
  required BigInt sessionId,
  required String annotationId,
}) => RustLib.instance.api.crateApiDocumentDeleteAnnotation(
  sessionId: sessionId,
  annotationId: annotationId,
);

String undo({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentUndo(sessionId: sessionId);

String redo({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDocumentRedo(sessionId: sessionId);

String exportAnnotations({required BigInt sessionId}) => RustLib.instance.api
    .crateApiDocumentExportAnnotations(sessionId: sessionId);

void saveAnnotations({
  required BigInt sessionId,
  required String databasePath,
}) => RustLib.instance.api.crateApiDocumentSaveAnnotations(
  sessionId: sessionId,
  databasePath: databasePath,
);

String loadAnnotations({
  required BigInt sessionId,
  required String databasePath,
}) => RustLib.instance.api.crateApiDocumentLoadAnnotations(
  sessionId: sessionId,
  databasePath: databasePath,
);

class CameraState {
  final double centerX;
  final double centerY;
  final double centerZ;
  final double scale;
  final double yaw;
  final double pitch;
  final bool perspective;

  const CameraState({
    required this.centerX,
    required this.centerY,
    required this.centerZ,
    required this.scale,
    required this.yaw,
    required this.pitch,
    required this.perspective,
  });

  static Future<CameraState> default_() =>
      RustLib.instance.api.crateApiDocumentCameraStateDefault();

  @override
  int get hashCode =>
      centerX.hashCode ^
      centerY.hashCode ^
      centerZ.hashCode ^
      scale.hashCode ^
      yaw.hashCode ^
      pitch.hashCode ^
      perspective.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraState &&
          runtimeType == other.runtimeType &&
          centerX == other.centerX &&
          centerY == other.centerY &&
          centerZ == other.centerZ &&
          scale == other.scale &&
          yaw == other.yaw &&
          pitch == other.pitch &&
          perspective == other.perspective;
}

class DocumentEventInfo {
  final String kind;
  final String stage;
  final double progress;
  final String? message;
  final BigInt? sessionId;

  const DocumentEventInfo({
    required this.kind,
    required this.stage,
    required this.progress,
    this.message,
    this.sessionId,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      stage.hashCode ^
      progress.hashCode ^
      message.hashCode ^
      sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentEventInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          stage == other.stage &&
          progress == other.progress &&
          message == other.message &&
          sessionId == other.sessionId;
}

class FormatInfo {
  final String id;
  final String displayName;
  final List<String> extensions;
  final String sceneKind;
  final String supportLevel;
  final bool available;
  final bool canMeasure;
  final String? note;

  const FormatInfo({
    required this.id,
    required this.displayName,
    required this.extensions,
    required this.sceneKind,
    required this.supportLevel,
    required this.available,
    required this.canMeasure,
    this.note,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      extensions.hashCode ^
      sceneKind.hashCode ^
      supportLevel.hashCode ^
      available.hashCode ^
      canMeasure.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          extensions == other.extensions &&
          sceneKind == other.sceneKind &&
          supportLevel == other.supportLevel &&
          available == other.available &&
          canMeasure == other.canMeasure &&
          note == other.note;
}

class HitResult {
  final BigInt entityId;
  final BigInt layerId;
  final double distance;
  final String entityKind;

  const HitResult({
    required this.entityId,
    required this.layerId,
    required this.distance,
    required this.entityKind,
  });

  @override
  int get hashCode =>
      entityId.hashCode ^
      layerId.hashCode ^
      distance.hashCode ^
      entityKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HitResult &&
          runtimeType == other.runtimeType &&
          entityId == other.entityId &&
          layerId == other.layerId &&
          distance == other.distance &&
          entityKind == other.entityKind;
}

class OpenDocumentResponse {
  final BigInt sessionId;
  final String formatId;
  final String sceneKind;
  final String displayName;
  final String fingerprint;
  final String documentJson;
  final BigInt totalEntityCount;
  final bool isPartial;

  const OpenDocumentResponse({
    required this.sessionId,
    required this.formatId,
    required this.sceneKind,
    required this.displayName,
    required this.fingerprint,
    required this.documentJson,
    required this.totalEntityCount,
    required this.isPartial,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      formatId.hashCode ^
      sceneKind.hashCode ^
      displayName.hashCode ^
      fingerprint.hashCode ^
      documentJson.hashCode ^
      totalEntityCount.hashCode ^
      isPartial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenDocumentResponse &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          formatId == other.formatId &&
          sceneKind == other.sceneKind &&
          displayName == other.displayName &&
          fingerprint == other.fingerprint &&
          documentJson == other.documentJson &&
          totalEntityCount == other.totalEntityCount &&
          isPartial == other.isPartial;
}

class OpenTicket {
  final BigInt ticketId;

  const OpenTicket({required this.ticketId});

  @override
  int get hashCode => ticketId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenTicket &&
          runtimeType == other.runtimeType &&
          ticketId == other.ticketId;
}

class SnapResult {
  final BigInt entityId;
  final double x;
  final double y;
  final String snapKind;
  final double distance;

  const SnapResult({
    required this.entityId,
    required this.x,
    required this.y,
    required this.snapKind,
    required this.distance,
  });

  @override
  int get hashCode =>
      entityId.hashCode ^
      x.hashCode ^
      y.hashCode ^
      snapKind.hashCode ^
      distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapResult &&
          runtimeType == other.runtimeType &&
          entityId == other.entityId &&
          x == other.x &&
          y == other.y &&
          snapKind == other.snapKind &&
          distance == other.distance;
}

class ViewportInfo {
  final BigInt viewportId;
  final PlatformInt64 textureId;
  final String rendererBackend;
  final int width;
  final int height;
  final double pixelRatio;

  const ViewportInfo({
    required this.viewportId,
    required this.textureId,
    required this.rendererBackend,
    required this.width,
    required this.height,
    required this.pixelRatio,
  });

  @override
  int get hashCode =>
      viewportId.hashCode ^
      textureId.hashCode ^
      rendererBackend.hashCode ^
      width.hashCode ^
      height.hashCode ^
      pixelRatio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportInfo &&
          runtimeType == other.runtimeType &&
          viewportId == other.viewportId &&
          textureId == other.textureId &&
          rendererBackend == other.rendererBackend &&
          width == other.width &&
          height == other.height &&
          pixelRatio == other.pixelRatio;
}
